name: Build

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HYDROFOIL_IMAGE: ghcr.io/luislavena/hydrofoil-crystal:1.3

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Build static executable
        run: docker run --rm -v ${{ github.workspace }}:/app -w /app -u $(id -u):$(id -g) $HYDROFOIL_IMAGE shards build --stats --release --static

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: hello-static-${{ runner.os }}
          path: bin/hello
